# Generated by Django 6.0.3 on 2026-04-13 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('suppliers', '0001_add_supplier_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
