# Generated by Django 6.0.3 on 2026-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('DNI', 'DNI'), ('CC', 'Cédula de ciudadanía'), ('PAS', 'Pasaporte'), ('RUC', 'RUC / NIT')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('doc_number', models.CharField(max_length=30, unique=True, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección particular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
