# Generated by Django 6.0.3 on 2026-04-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CC', 'Cédula de identidad'), ('PAS', 'Pasaporte'), ('RUC', 'RUC / NIT')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='info@info.com', max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
