# Generated by Django 6.0.3 on 2026-04-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_add_supplier_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cotización USD (Gs.)')),
                ('fields_data', models.JSONField(default=dict, verbose_name='Valores')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total USD')),
                ('total_gs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gs.')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_config', models.JSONField(default=list, help_text='Lista de objetos con: key, label, type (number|percent|auto), default, base (para percent), formula (para auto), in_total (bool).', verbose_name='Configuración de campos')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_config', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Config. de presupuesto',
                'verbose_name_plural': 'Config. de presupuestos',
            },
        ),
    ]
