# Generated by Django 6.0.3 on 2026-04-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción del producto'),
        ),
    ]
