# Generated by Django 6.0.3 on 2026-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TRF', 'Transferencia'), ('TAR', 'Tarjeta'), ('DSC', 'Descuento')], default='EFE', max_length=3, verbose_name='Tipo de pago'),
        ),
    ]
