# Generated by Django 5.2.14 on 2026-10-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productsize'),
        ('sales', '0003_saleitem_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='description',
            field=models.CharField(blank=True, help_text='Solo para líneas sin producto: un servicio, una deuda, etc.', max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), models.Q(('description', ''), _negated=True), _connector='OR'), name='saleitem_product_or_description'),
        ),
    ]
