# Generated by Django 6.0.3 on 2026-04-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('GEN', 'General'), ('CAL', 'Calzado'), ('VES', 'Vestimenta')], default='GEN', max_length=3, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de lista')),
                ('distributor_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio distribuidor')),
                ('calce', models.CharField(blank=True, choices=[('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49')], help_text='Solo para categoría Calzado', max_length=5, verbose_name='Calce')),
                ('talle', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], help_text='Solo para categoría Vestimenta', max_length=5, verbose_name='Talle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['description'],
            },
        ),
    ]
