# Generated by Django 6.0.3 on 2026-04-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo USD'),
        ),
        migrations.AddField(
            model_name='product',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización (USD→Gs.)'),
        ),
    ]
