# Generated by Django 6.0.3 on 2026-04-13 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_cost_usd_cotizacion'),
        ('suppliers', '0001_add_supplier_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='Procedencia'),
        ),
    ]
