# Generated by Django 6.0.3 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_supplier_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calce_uk',
            field=models.CharField(blank=True, help_text='Talla británica', max_length=5, verbose_name='Calce UK'),
        ),
        migrations.AddField(
            model_name='product',
            name='calce_us',
            field=models.CharField(blank=True, help_text='Talla americana', max_length=5, verbose_name='Calce US'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calce',
            field=models.CharField(blank=True, choices=[('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49')], help_text='Talla europea/latinoamericana', max_length=5, verbose_name='Calce EU'),
        ),
    ]
