# Generated by Django 6.0.3 on 2026-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_calce_us_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calce_uk',
            field=models.CharField(blank=True, choices=[('5', 'UK 5'), ('5.5', 'UK 5.5'), ('6', 'UK 6'), ('6.5', 'UK 6.5'), ('7', 'UK 7'), ('7.5', 'UK 7.5'), ('8', 'UK 8'), ('8.5', 'UK 8.5'), ('9', 'UK 9'), ('9.5', 'UK 9.5'), ('10', 'UK 10'), ('10.5', 'UK 10.5'), ('11', 'UK 11'), ('11.5', 'UK 11.5'), ('12', 'UK 12'), ('12.5', 'UK 12.5'), ('13', 'UK 13')], help_text='Talla británica', max_length=5, verbose_name='Calce UK'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calce_us',
            field=models.CharField(blank=True, choices=[('5', 'US 5'), ('5.5', 'US 5.5'), ('6', 'US 6'), ('6.5', 'US 6.5'), ('7', 'US 7'), ('7.5', 'US 7.5'), ('8', 'US 8'), ('8.5', 'US 8.5'), ('9', 'US 9'), ('9.5', 'US 9.5'), ('10', 'US 10'), ('10.5', 'US 10.5'), ('11', 'US 11'), ('11.5', 'US 11.5'), ('12', 'US 12'), ('12.5', 'US 12.5'), ('13', 'US 13'), ('13.5', 'US 13.5'), ('14', 'US 14')], help_text='Talla americana', max_length=5, verbose_name='Calce US'),
        ),
    ]
